files:
  path: /files/{file}
  defaults:
    _controller: InspiredMinds\ContaoFileAccessBundle\Controller\FilesController::fileAction
    _scope: frontend
    _token_check: true
  requirements:
    file: .+
