services:
  InspiredMinds\ContaoFileAccessBundle\Controller\FilesController:
    arguments:
      - '%kernel.project_dir%'
      - '@session'
      - '@contao.framework'
    tags: ['controller.service_arguments']
