services:
  InspiredMinds\ContaoFileAccessBundle\Controller\FilesController:
    arguments:
      - '%kernel.project_dir%'
      - '@session'
      - '@contao.framework'
      - '@security.helper'
    tags: ['controller.service_arguments']

  InspiredMinds\ContaoFileAccessBundle\DataContainer\FilesCallbacks:
    autoconfigure: true
